use_frameworks!

platform :ios, '8.0'

target 'LQCommonKit_Example' do
  pod 'AFNetworking'
  #pod 'SocketRocket'
  pod 'LQCommonKit', :path => 'Lib/LQCommonKit'
  target 'LQCommonKit_Tests' do
    inherit! :search_paths

    
  end
end
